#!/bin/bash

#Este es mi primer proyecto. Se que tiene mucho, pero que mucho que mejorar.
#En este script no se escribe codigos de terceros, todo el codigo ha sido
#creado por mi (Dergli) aunque si es cierto que he añadido llamadas a programas
#de terceros. Pero el codigo de estos programas de terceros no han sido modificados
#ni manipulados, es decir, los programas son los mismos si nos los descargamos independientemente.
#Me gustaría encontrar participacion en este proyectos y ayudas de sus conocimientos para poder
#ir completando este proyecto poco a poco, como puede ser por ejemplo, un modulo para comprobar
#la seguridad de tus claves WiFi, entre otras cosas. Tambien crear un SpoofMail con un formulario
#y la correcta configuracion del servidor local con php para hacer los envios desde la maquina local
#Todas las criticas he ideas son bien recividas, y si quereis formar parte del proyecto a traves de
#git sois bienvenidos. (Si teneis conocimientos de git mejor, ya que tambien soy nuevo en el control
#de versiones)
#Si quereis modificar el codigo o compartir estais en vuestro derecho, lo unico que pido es que se
#nombre de donde ha salido la idea principal y el paquete principal el cual habeis modificado

#####################################################################
#Autor: Dergli							    #
#PaginaWeb: En construccion					    #
#Email de contacto:		dergli@hushmail.com		    #
#								    #
#								    #
#####################################################################



#Para finalizar ya todo este toston, simplemete agradeceros el tiempo empleado en descargar este proyecto
#y ver como funciona.






while
clear

#-----------FUNCIONES----------------------
#Creamos el banner de inicio
banner()
{
echo "

@@@  @@@   @@@@@@    @@@@@@@  @@@  @@@   @@@@@@      @@@@@@@   @@@@@@@@  @@@@@@@    @@@@@@@@  @@@       @@@
@@@  @@@  @@@@@@@@  @@@@@@@@  @@@  @@@  @@@@@@@      @@@@@@@@  @@@@@@@@  @@@@@@@@  @@@@@@@@@  @@@       @@@
@@!  @@@  @@!  @@@  !@@       @@!  !@@  !@@          @@!  @@@  @@!       @@!  @@@  !@@        @@!       @@!
!@!  @!@  !@!  @!@  !@!       !@!  @!!  !@!          !@!  @!@  !@!       !@!  @!@  !@!        !@!       !@!
@!@!@!@!  @!@!@!@!  !@!       @!@@!@!   !!@@!!       @!@  !@!  @!!!:!    @!@!!@!   !@! @!@!@  @!!       !!@
!!!@!!!!  !!!@!!!!  !!!       !!@!!!     !!@!!!      !@!  !!!  !!!!!:    !!@!@!    !!! !!@!!  !!!       !!!
!!:  !!!  !!:  !!!  :!!       !!: :!!        !:!     !!:  !!!  !!:       !!: :!!   :!!   !!:  !!:       !!:
:!:  !:!  :!:  !:!  :!:       :!:  !:!      !:!      :!:  !:!  :!:       :!:  !:!  :!:   !::   :!:      :!:
::   :::  ::   :::   ::: :::   ::  :::  :::: ::       :::: ::   :: ::::  ::   :::   ::: ::::   :: ::::   ::
 :   : :   :   : :   :: :: :   :   :::  :: : :       :: :  :   : :: ::    :   : :   :: :: :   : :: : :  :

"

}
#******METASPLOIT*******
# Iniciamos los servios de metasploit
metasploit_init()
{
service postgresql start
service metasploit start
service apache2 start
}
# Detemos los servicios de metasploit
metasploit_fin()
{
service postgresql stop
service metasploit stop
service apache2 stop
}
# Detenemos todos los servicios
services_stop()
{
service apache2 stop
service mysql stop
service metasploit stop
service postfix stop
service postgresql stop
}
#******************* INSTALACION DE PROGRAMAS
# Programas principales
fn_installn()
{
apt-get install dhcpd
apt-get install network-network
apt-get install apache2
apt-get install mysql-server
}
# Programas Mestasploit
fn_metainstal()
{
apt-get install metasploit
apt-get install metasploit-framework
apt-get install armitage
}
# Programas Phising
fn_phisintal()
{
git clone https://github.com/trustedsec/social-engineer-toolkit/ set/
git clone https://github.com/sptoolkit/sptoolkit /var/www/
}
# Programas EMAIL
fn_emailinstal()
{
apt-get install squirrelmail
apt-get install postfix
apt-get install swaks
}
# Programas Fake AP
fn_fakeapinstal()
{
cd /home/HacksDergli/easy-creds
./installer.sh
apt-get install yersinia
}
 
banner

echo 1.- Configurar IP DMZ
echo 2.- Iniciar Metasploit
echo 3.- Phising
echo 4.- Servidor MAIL
echo 5.- Crear FakeAP/Hacer MITM
echo 6.- Telefonia Virtual/SpoofSMS
echo 7.- Anonimato //Proximamente
echo 8.- Programas necesarios
echo 0.- Detener todos los servicios
echo q.- Salir

read VAR
clear
do
#Configuramos la IP
if [ "$VAR" = "1" ]; then
banner
echo 1.- Configurar IP por cable
echo 2.- Configurar IP Wireless
echo 3.- Configurar visualmente
echo Pulsar enter para volver al menu
	read VAR
	clear
	#Configuracion para red Ethernet
	if [ "$VAR" = "1" ]
	then
	/etc/init.d/network-manager stop
	clear
	echo "Introduce la interfaz (eth0)"
	read IT
	ifconfig $IT up
	echo Introduce la IP
	read IP
	echo Introduce la mascara
	read NM
	ifconfig $IT $IP netmask $NM 
	echo Introduce la puerta de enlace
	read GW
	route add -net 0.0.0.0 gw $GW netmask 255.255.255.0
	echo -e "nameserver 8.8.8.8 \nnameserver 8.8.4.4\n" > /etc/resolv.conf 
	dhclient -r
	dhclient $IT
	sleep 2
	#Configuracion para red Wireless
	elif [ "$VAR" = "2" ]
	then
	/etc/init.d/network-manager stop
	ifup lo
	clear
	iwconfig
	echo "Introduce la interfaz (wlan0)"
	read IT
	ifconfig $IT up
	clear
	iwlist $IT scan
	sleep 10
	clear
	#Configuracion seguridad Wireless
	echo 1.- Seguridad WEP
	echo 2.- Seguridad WPA
	echo 3.- Abierta
	echo Pulsa enter para volver al menu principal
	read VAR
		#Configuracion WEP
		if [ "$VAR" = "1" ]
		then
		echo Introduce el nombre de la red
		read AP
		iwconfig $IT essid $AP
		echo Introducir contraseña
		read PASS
		iwconfig $IT key $PASS
		echo Introduce la IP
		read IP
		echo Introduce la mascara
		read NM
		ifconfig $IT $IP netmask $NM
		echo Introduce la puerta de enlace 
		read GW
		route add -net 0.0.0.0 gw $GW netmask 255.255.255.0 $IT
		echo -e "nameserver 8.8.8.8 \nnameserver 8.8.4.4\n" > /etc/resolv.conf 
		dhclient -r
		dhclient $IT
		#Configuracion WPA
		elif [ "$VAR" = "2" ]
		then
		echo Introduce el nombre de la red
		read AP
		echo Introduce la clave
		read PASS
		wpa_passphrase $AP $PASS > /root/wpa.conf
		wpa_supplicant -B -Dwext -i $IT -c/root/wpa.conf
		#/echo Introduce la IP
		#read IP
		#echo Introduce la mascara
		#read NM
		#ifconfig $IT $IP netmask $NM
		#echo Introduce la puerta de enlace
		#read GW
		#route add -net 0.0.0.0 gw $GW netmask 0.0.0.0 $IT
		#echo -e "nameserver 8.8.8.8 \nnameserver 8.8.4.4\n" > /etc/resolv.conf
		dhclient -r
		dhclient $IT
		elif [ "$VAR" = "3" ]
		then
		echo Proximamente
		fi
	elif [ "$VAR" = "3" ]
	then 
	/etc/init.d/network-manager start
	fi
elif [ "$VAR" = "2" ]; then
banner
echo 1.- Actualizar Metasploit
echo 2.- Iniciar servicios Metasploit y Metasploit
echo 3.- Iniciar servicios Metasploit
echo 4.- Iniciar servicios Metasploit y Armitage
echo 5.- Detener servicios Metasploit
echo Pulsar enter para volver al menu
	read VAR
	clear
	if [ "$VAR" = "1" ]
	then
	msfupdate
	elif [ "$VAR" = "2" ]
	then
	metasploit_init
	msfconsole
	elif [ "$VAR" = "3" ]
	then
	metasploit_init 
	elif [ "$VAR" = "4" ]
	then
	metasploit_init
	armitage
	elif [ "$VAR" = "5" ]
	then
	metasploit_fin
	fi
elif [ "$VAR" = "3" ]; then
banner
echo 1.- Phising con Setoolkit
echo 2.- SPTollkit
echo Pulsar enter para volver al menu
	read VAR
	clear
	if [ "$VAR" = "1" ]
	then
	service apache2 stop
	setoolkit
	elif [ "$VAR" = "2" ]
	then
	service apache2 start
	service mysql start
	firefox -new-window http://127.0.0.1/spt
	fi
elif [ "$VAR" = "4" ]; then
banner
echo 1.- Configurar servidor EMAIL
echo 2.- Iniciar servidor EMAIL
echo 3.- Detener servidor EMAIL
echo 4.- Spoofear direcion EMAIL
echo "5.- Spoofear direccion EMAIL (Con adjuntos)"
echo "6.- Spoofear direccion EMAIL (SWAKS)"
echo Pulsar enter para volver al menu
	read VAR
	clear
	if [ "$VAR" = "1" ]
	then
	squirrelmail-configure
	elif [ "$VAR" = "2" ]
	then
	service apache2 start
	service postfix start
	firefox -new-window http://127.0.0.1/squirrelmail &
	elif [ "$VAR" = "3" ]
	then
	service apache2 stop
	service postfix stop
	elif [ "$VAR" = "4" ]
	then
	firefox -new-window http://www.filosofia.mx/index.php?/perse/enviar-amigo/1804 &
	elif [ "$VAR" = "5" ]
	then
	firefox -new-window http://emkei.cz/ &
	elif [ "$VAR" = "6" ]
	then
	echo Introduce la direccion del receptor
	read DEM
	echo Introduce la direccion del emisor
	read DRE
	echo Introduce el asunto del EMAIL
	read ASU
	echo Introduce el cuerpo del mensaje
	read CUER
	swaks --to $DEM --from $DRE  --header "Subject: $ASU" --body "$CUER"
	fi
elif [ "$VAR" = "5" ]; then
banner
echo 1.- Configurar manualmente
echo 2.- Iniciar FakeAP PwnStart
echo 3.- Iniciar FakeAP easy-creds
echo 4.- Hacer ataque MITM a VLAN/VPN
echo Pulsar enter para volver al menu
	read VAR
	clear
	if [ "$VAR" = "1" ]
	then
	echo Aun no disponible
	elif [ "$VAR" = "2" ]
	then
	cd /home/HacksDergli
	./PwnSTAR_0.9
	elif [ "$VAR" = "3" ]
	then
	easy-creds
	elif [ "$VAR" = "4" ]
	then
	yersinia -G &
	fi
elif [ "$VAR" = "6" ]; then
banner
echo 1.- Telefonia virtual
echo 2.- SpooferSMS
echo Pulsar enter para volver al menu
	read VAR
	clear
	if [ "$VAR" = "1" ]
	then
	echo 1.- FonYou
	echo 2.- Yuilop
	echo 3.- UppTalk
		read VAR
		clear
		if [ "$VAR" = "1" ]
		then
		firefox -new-window http://www.fonyou.es/ &
		elif [ "$VAR" = "2" ]
		then
		firefox -new-window http://yuilop.com/es/ &
		elif [ "$VAR" = "3" ]
		then
		firefox -new-window http://upptalk.com/ &
		fi
	elif [ "$VAR" = "2" ]
	then
	firefox -new-window http://www.lleida.net/es &
	fi
elif [ "$VAR" = "7"; then
banner
echo 1.- Instalar
echo 2.- Tor
echo 3.- FreeNet
	read VAR

elif [ "$VAR" = "8" ]; then
banner
echo 1.- Instalar
echo Pulsa enter para volver al menu
#echo 2.- Actualizar
	read VAR
	clear
	if [ "$VAR" = "1" ]
	then
	echo 1.- Instalar programas necesarios generales
	echo 2.- Instalar programas Metasploit
	echo 3.- Instalar programas Phising
	echo 4.- Instalar progrmas necesarios EMAIL
	echo 5.- Instalar programas FakeAP
	echo 6.- Instalar todos
	read VAR
		if [ "$VAR" = "1" ]; then
		fn_installn
		elif [ "$VAR" = "2" ]
		then
		fn_metainstal
		elif [ "$VAR" = "3" ]
		then
		fn_phisintal
		elif [ "$VAR" = "4" ]
		then
		fn_emailinstal
		elif [ " $VAR" = "5" ]
		then
		fn_fakeapinstal
		elif [ "$VAR" = "6" ]
		then
		fn_installn
		fn_metainstal
		fn_phisintal
		fn_emailinstal
		fn_fakeapinstal
	#echo Proximamente
	#apt-get install mysql
	#apt-get install apache2
	#apt-get install postfix
		fi
	fi
elif [ "$VAR" = "0" ]; then
services_stop
elif [ "$VAR" = q ]; then
echo Sugerencias dergli@hushmail.com
exit
fi
done
